# Generated by Django 5.0.14 on 2025-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westige", "0002_orders_address_orders_product_orders_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
