# Generated by Django 5.0.14 on 2026-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westige", "0003_alter_orders_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="p_image",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
    ]
