# Generated by Django 5.0.14 on 2026-01-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westige", "0004_products_p_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="p_image",
            field=models.ImageField(blank=True, null=True, upload_to="product/"),
        ),
    ]
