# Generated by Django 5.0.14 on 2026-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("westige", "0005_alter_products_p_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cod", "Cash On Delivery"), ("online", "Online")],
                max_length=250,
                null=True,
            ),
        ),
    ]
