# Generated by Django 5.0.14 on 2026-01-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("westige", "0006_orders_payment_method"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
